import json
import sqlite3
from os import path

conn = sqlite3.connect('db_test.db')

conn.execute("CREATE TABLE ProductTest (collection, category, category_ru, product_full_name, product_type, product_img, is_new, available_for_delivery_2, available_for_delivery_28, available_in_showroom, description, price, price_sale, fabric_type, fabric_name, product_fabric_about, product_fabric_img, carousel_item_1, carousel_item_2, carousel_item_3, carousel_item_4, carousel_item_5, carousel_item_1_mob, carousel_item_2_mob, carousel_item_3_mob, carousel_item_4_mob, carousel_item_5_mob, closeup, slider_interior_1, slider_interior_2, slider_interior_3, slider_interior_4, slider_interior_1_mob, slider_interior_2_mob, slider_interior_3_mob, slider_interior_4_mob, width, depth, height, scheme, features);")
with open('data.json', 'r') as data_file:
    data = json.load(data_file)
    for item in data:
     conn.execute("INSERT INTO ProductTest (collection, category, category_ru, product_full_name, product_type, product_img, is_new, available_for_delivery_2, available_for_delivery_28, available_in_showroom, description, price, price_sale, fabric_type, fabric_name, product_fabric_about, product_fabric_img, carousel_item_1, carousel_item_2, carousel_item_3, carousel_item_4, carousel_item_5, carousel_item_1_mob, carousel_item_2_mob, carousel_item_3_mob, carousel_item_4_mob, carousel_item_5_mob, closeup, slider_interior_1, slider_interior_2, slider_interior_3, slider_interior_4, slider_interior_1_mob, slider_interior_2_mob, slider_interior_3_mob, slider_interior_4_mob, width, depth, height, scheme, features) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", (item['collection'], item['category'], item['category_ru'], item['product_full_name'], item['product_type'], item['product_img'], item['is_new'], item['available_for_delivery_2'], item['available_for_delivery_28'], item['available_in_showroom'], item['description'], item['price'], item['price_sale'], item['fabric_type'], item['fabric_name'], item['product_fabric_about'], item['product_fabric_img'], item['carousel_item_1'], item['carousel_item_2'], item['carousel_item_3'], item['carousel_item_4'], item['carousel_item_5'], item['carousel_item_1_mob'], item['carousel_item_2_mob'], item['carousel_item_3_mob'], item['carousel_item_4_mob'], item['carousel_item_5_mob'], item['closeup'], item['slider_interior_1'], item['slider_interior_2'], item['slider_interior_3'], item['slider_interior_4'], item['slider_interior_1_mob'], item['slider_interior_2_mob'],item['slider_interior_3_mob'], item['slider_interior_4_mob'], item['width'], item['depth'], item['height'], item['scheme'], item['features']))
conn.commit()
conn.close()


    # instance = Product(collection=entry['collection'], category=entry['category'], category_ru=entry['category_ru'], name=entry['product_full_name'], product_type=entry['product_type'], product_img=entry['product_img'], description=entry['description'], price=entry['price'], price_sale=entry['price_sale'], fabric_type=entry['fabric_type'], fabric_name=entry['fabric_name'], product_fabric_about=entry['product_fabric_about'], product_fabric_img=entry['product_fabric_img'], carousel_item_1=entry['carousel_item_1'], carousel_item_2=entry['carousel_item_2'], carousel_item_3=entry['carousel_item_3'], carousel_item_4=entry['carousel_item_4'], carousel_item_5=entry['carousel_item_5'], carousel_item_1_mob=entry['carousel_item_1_mob'], carousel_item_2_mob=entry['carousel_item_2_mob'], carousel_item_3_mob=entry['carousel_item_3_mob'], carousel_item_4_mob=entry['carousel_item_4_mob'], carousel_item_5_mob=entry['carousel_item_5_mob'], closeup=entry['closeup'], slider_interior_1=entry['slider_interior_1'],slider_interior_2=entry['slider_interior_2'], slider_interior_3=entry['slider_interior_3'], slider_interior_4=entry['slider_interior_4'], slider_interior_1_mob=entry['slider_interior_1_mob'],slider_interior_2_mob=entry['slider_interior_2_mob'], slider_interior_3_mob=entry['slider_interior_3_mob'], slider_interior_4_mob=entry['slider_interior_4_mob'],  prod_width=entry['width'], prod_depth=entry['depth'], prod_height=entry['height'], scheme=entry['scheme'], features=entry['features'])

 # instance.save()
