# Generated by Django 4.1.12 on 2023-11-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('category_ru', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['collection'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('fabric_id', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_name', models.CharField(max_length=50)),
                ('product_fabric_icon', models.CharField(max_length=250)),
                ('product_fabric_img', models.CharField(max_length=250)),
                ('product_fabric_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
                'ordering': ['fabric_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('fabric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.fabric')),
                ('collection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.collection')),
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.category')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_full_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('product_img', models.CharField(max_length=150)),
                ('popular', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True)),
                ('available_for_delivery_2', models.BooleanField(default=True)),
                ('available_for_delivery_28', models.BooleanField(default=True)),
                ('available_in_showroom', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=1500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carousel_item_1', models.CharField(max_length=250)),
                ('carousel_item_2', models.CharField(max_length=250)),
                ('carousel_item_3', models.CharField(max_length=250)),
                ('carousel_item_4', models.CharField(max_length=250)),
                ('carousel_item_5', models.CharField(max_length=250)),
                ('carousel_item_mob_1', models.CharField(max_length=250)),
                ('carousel_item_mob_2', models.CharField(max_length=250)),
                ('carousel_item_mob_3', models.CharField(max_length=250)),
                ('carousel_item_mob_4', models.CharField(max_length=250)),
                ('carousel_item_mob_5', models.CharField(max_length=250)),
                ('closeup', models.CharField(max_length=250)),
                ('slider_interior_1', models.CharField(max_length=250)),
                ('slider_interior_2', models.CharField(max_length=250)),
                ('slider_interior_3', models.CharField(max_length=250)),
                ('slider_interior_4', models.CharField(max_length=250)),
                ('slider_interior_1_mob', models.CharField(max_length=250)),
                ('slider_interior_2_mob', models.CharField(max_length=250)),
                ('slider_interior_3_mob', models.CharField(max_length=250)),
                ('slider_interior_4_mob', models.CharField(max_length=250)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('pdf', models.CharField(max_length=150)),
                ('product_inside', models.CharField(max_length=150)),
                ('product_inside_pillow', models.CharField(max_length=150)),
                ('carcas_type', models.CharField(max_length=50)),
                ('paws_type', models.CharField(max_length=50)),
                ('mechanism_type', models.CharField(max_length=50)),
                ('sleep_place', models.CharField(max_length=50)),
                ('linen_drawer', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=150)),
                ('features', models.CharField(max_length=350)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=350)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['product_full_name'],
            },
            bases=('product.category', 'product.collection', 'product.fabric'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['fabric_name'], name='product_fab_fabric__f5fc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection'], name='product_col_collect_386316_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='product_cat_categor_a164b2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='product_pro_id_b9e5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_full_name'], name='product_pro_product_63afbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='product_pro_created_942044_idx'),
        ),
    ]
