# Generated by Django 4.1.13 on 2023-12-19 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_ru', models.CharField(max_length=50, verbose_name='Название категории (по-русски, в МНОЖЕСТВЕННОМ числе)')),
                ('producttype', models.CharField(max_length=50, null=True, verbose_name='Название категории (то же, в ЕДИНСТВЕННОМ числе)')),
                ('category', models.CharField(max_length=30, verbose_name='Сокращенно латиницей (arm, str, k1r и т.п.)')),
                ('category_slug', models.SlugField(max_length=30, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=30, verbose_name='Коллекция (Латиницей, с большой буквы)')),
                ('collection_slug', models.SlugField(max_length=30, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['collection'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('fabric_id', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_name', models.CharField(max_length=50, verbose_name='Название ткани')),
                ('product_fabric_img', models.ImageField(upload_to='fabric_images/%Y/%m/%d', verbose_name='Образец ткани')),
                ('product_fabric_about', models.CharField(max_length=1500, verbose_name='Описание ткани')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
                'ordering': ['fabric_name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок опции (не обязательно)')),
                ('option_1_img', models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 1')),
                ('option_1_description', models.CharField(max_length=500, verbose_name='Описание опции 1')),
                ('option_2_img', models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 2')),
                ('option_2_description', models.CharField(max_length=500, verbose_name='Описание опции 2')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['option_name'],
            },
        ),
        migrations.CreateModel(
            name='PopOverFeatures',
            fields=[
                ('popover_id', models.AutoField(primary_key=True, serialize=False)),
                ('popover_name', models.CharField(blank=True, max_length=350, null=True, verbose_name='Название набора 5 фич')),
                ('popover_1_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 1')),
                ('popover_1_description', models.CharField(max_length=500, verbose_name='Описание фичи 1')),
                ('popover_2_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 2')),
                ('popover_2_description', models.CharField(max_length=500, verbose_name='Описание фичи 2')),
                ('popover_3_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 3')),
                ('popover_3_description', models.CharField(max_length=500, verbose_name='Описание фичи 3')),
                ('popover_4_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 4')),
                ('popover_4_description', models.CharField(max_length=500, verbose_name='Описание фичи 4')),
                ('popover_5_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 5')),
                ('popover_5_description', models.CharField(max_length=500, verbose_name='Описание фичи 5')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Фича поп-овер',
                'verbose_name_plural': 'Фичи поп-овер',
                'ordering': ['popover_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное название товара (напр. Угловой диван Consono)')),
                ('product_fabric_icon_1', models.ImageField(blank=True, default='fabric_icons/2023/12/06/CAMBRIDGE_600.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 1')),
                ('slug_fabric_icon_1', models.SlugField(max_length=100, null=True, verbose_name='Название ткани №1')),
                ('product_fabric_icon_2', models.ImageField(blank=True, default='fabric_icons/2023/12/06/JAZZ_01.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 2')),
                ('slug_fabric_icon_2', models.SlugField(max_length=100, null=True, verbose_name='Название ткани №2')),
                ('product_fabric_icon_3', models.ImageField(blank=True, default='fabric_icons/2023/12/06/JAZZ_21.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 3')),
                ('slug_fabric_icon_3', models.SlugField(max_length=100, null=True, verbose_name='Название ткани №3')),
                ('product_fabric_icon_4', models.ImageField(blank=True, default='fabric_icons/2023/12/06/PIXEL_FOREST.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 4')),
                ('slug_fabric_icon_4', models.SlugField(max_length=100, null=True, verbose_name='Название ткани №4')),
                ('product_fabric_icon_5', models.ImageField(blank=True, default='fabric_icons/2023/12/06/VELUTTO_32.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 5')),
                ('slug_fabric_icon_5', models.SlugField(max_length=100, null=True, verbose_name='Название ткани №5')),
                ('show_on_category_page', models.BooleanField(default=True, verbose_name='Отображать в выдаче категории')),
                ('popular', models.BooleanField(default=True, verbose_name='Отображать в карусели "Популярные"')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый')),
                ('available_for_delivery_2', models.BooleanField(default=True, verbose_name='Доставим за 2 дня')),
                ('available_for_delivery_28', models.BooleanField(default=True, verbose_name='Доставим за 28 дней')),
                ('available_in_showroom', models.BooleanField(default=True, verbose_name='Есть в шоуруме')),
                ('icon_is_new', models.FileField(blank=True, default='status_icons/2023/12/07/new.svg', null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Новый')),
                ('icon_available_for_delivery_2', models.FileField(blank=True, default='status_icons/2023/12/07/delivery2.svg', null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Доставим за 2 дня')),
                ('icon_available_for_delivery_28', models.FileField(blank=True, default='status_icons/2023/12/07/delivery2.svg', null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Доставим за 28 дней')),
                ('icon_available_in_showroom', models.FileField(blank=True, default='status_icons/2023/12/07/showrooms.svg', null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Есть в шоуруме')),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение товара')),
                ('description', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (распродажа)')),
                ('closeup', models.ImageField(blank=True, null=True, upload_to='closeups/', verbose_name='Крупный фрагмент справа')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('pdf', models.FileField(blank=True, default='status_icons/2023/12/07/new.svg', null=True, upload_to='pdf/%Y/%m/%d', verbose_name='Файл PDF')),
                ('product_inside', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение')),
                ('product_inside_pillow', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение подушек')),
                ('carcas_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Каркас')),
                ('paws_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ножки')),
                ('mechanism_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Механизм')),
                ('sleep_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место')),
                ('linen_drawer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бельевой ящик')),
                ('scheme', models.FileField(blank=True, default='status_icons/2023/12/07/new.svg', null=True, upload_to='schemes/%Y/%m/%d', verbose_name='Схема')),
                ('features', models.CharField(blank=True, max_length=350, null=True, verbose_name='Конструктивные особенности')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
                ('product_slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['product_full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_items/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SliderInterior',
            fields=[
                ('sl_interior_id', models.AutoField(primary_key=True, serialize=False)),
                ('sl_interior_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название слайдера (коллекция)')),
                ('sl_interior_1_img', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 1 | десктоп')),
                ('sl_interior_2_img', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 2 | десктоп')),
                ('sl_interior_3_img', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 3 | десктоп')),
                ('sl_interior_4_img', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 4 | десктоп')),
                ('sl_interior_1_img_mob', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 1 | мобильный')),
                ('sl_interior_2_img_mob', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 2 | мобильный')),
                ('sl_interior_3_img_mob', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 3 | мобильный')),
                ('sl_interior_4_img_mob', models.ImageField(upload_to='interiors/%Y/%m/%d', verbose_name='Изображение 4 | мобильный')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Слайдер с интерьерами',
                'verbose_name_plural': 'Слайдеры с интерьерами',
                'ordering': ['sl_interior_name'],
            },
        ),
        migrations.AddIndex(
            model_name='sliderinterior',
            index=models.Index(fields=['sl_interior_name'], name='product_sli_sl_inte_f3f0fc_idx'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.option'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_items',
            field=models.ManyToManyField(blank=True, related_name='carousel_items', to='product.productimage', verbose_name='Слайдер с товаром | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_items_mob',
            field=models.ManyToManyField(blank=True, related_name='carousel_items_mob', to='product.productimage', verbose_name='Слайдер с товаром | мобильный'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.fabric', verbose_name='Название ткани'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.option', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='product',
            name='popover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.popoverfeatures', verbose_name='Поповер фичи'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.sliderinterior', verbose_name='Слайдер с интерьерами'),
        ),
        migrations.AddField(
            model_name='popoverfeatures',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='popoverfeatures',
            name='collection',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.collection', verbose_name='Коллекция'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['option_name'], name='product_opt_option__ae3011_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['fabric_name'], name='product_fab_fabric__f5fc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection'], name='product_col_collect_386316_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='product_cat_categor_a164b2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'product_slug', '-created'], name='product_pro_id_d2cb84_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_full_name'], name='product_pro_product_63afbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='product_pro_created_942044_idx'),
        ),
        migrations.AddIndex(
            model_name='popoverfeatures',
            index=models.Index(fields=['popover_name'], name='product_pop_popover_de2627_idx'),
        ),
    ]
