# Generated by Django 4.1.12 on 2023-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_mob_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_mob_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_mob_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_mob_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel_item_mob_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='closeup',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_1_mob',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_2_mob',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_3_mob',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_4_mob',
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_items',
            field=models.ManyToManyField(related_name='carousel_items', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_items_mob',
            field=models.ManyToManyField(related_name='carousel_items_mob', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior',
            field=models.ManyToManyField(related_name='slider_interior', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_mob',
            field=models.ManyToManyField(related_name='slider_interior_mob', to='product.productimage'),
        ),
    ]
