# Generated by Django 5.0 on 2023-12-06 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopOverFeatures',
            fields=[
                ('popover_id', models.AutoField(primary_key=True, serialize=False)),
                ('popover_name', models.CharField(blank=True, max_length=350, null=True, verbose_name='Название фичи')),
                ('popover_1_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 1')),
                ('popover_1_description', models.CharField(max_length=500, verbose_name='Описание фичи 1')),
                ('popover_2_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 2')),
                ('popover_2_description', models.CharField(max_length=500, verbose_name='Описание фичи 2')),
                ('popover_3_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 3')),
                ('popover_3_description', models.CharField(max_length=500, verbose_name='Описание фичи 3')),
                ('popover_4_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 4')),
                ('popover_4_description', models.CharField(max_length=500, verbose_name='Описание фичи 4')),
                ('popover_5_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 5')),
                ('popover_5_description', models.CharField(max_length=500, verbose_name='Описание фичи 5')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Фича поп-овер',
                'verbose_name_plural': 'Фичи поп-овер',
                'ordering': ['popover_name'],
            },
        ),
        migrations.CreateModel(
            name='SliderInterior',
            fields=[
                ('slint_id', models.AutoField(primary_key=True, serialize=False)),
                ('slint_name', models.CharField(max_length=350, verbose_name='Название слайдера')),
                ('slint_img_1', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 1')),
                ('slint_img_2', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 2')),
                ('slint_img_3', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 3')),
                ('slint_img_4', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 4')),
                ('slint_img_mob_1', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 1')),
                ('slint_img_mob_2', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 2')),
                ('slint_img_mob_3', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 3')),
                ('slint_img_mob_4', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 4')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Слайдер с интерьерами',
                'verbose_name_plural': 'Слайдеры с интерьерами',
                'ordering': ['slint_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_fabric_icon',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_id_7c37c2_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_mob',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=30, null=True, unique=True, verbose_name='Повторите'),
        ),
        migrations.AddField(
            model_name='category',
            name='producttype',
            field=models.CharField(max_length=50, null=True, verbose_name='Название категории (то же, в ЕДИНСТВЕННОМ числе)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(max_length=30, null=True, unique=True, verbose_name='Повторите'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последние изменения'),
        ),
        migrations.AddField(
            model_name='option',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='option',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_4',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_5',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_category_page',
            field=models.BooleanField(default=True, verbose_name='Отображать в выдаче категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fabric_icon_1',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Название ткани №1'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fabric_icon_2',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Название ткани №2'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fabric_icon_3',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Название ткани №3'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fabric_icon_4',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Название ткани №4'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fabric_icon_5',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Название ткани №5'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30, verbose_name='Сокращенно латиницей (arm, str, k1r и т.п.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=50, verbose_name='Название категории (по-русски, в МНОЖЕСТВЕННОМ числе)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(max_length=30, verbose_name='Коллекция (Латиницей)'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_name',
            field=models.CharField(max_length=50, verbose_name='Название ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_about',
            field=models.CharField(max_length=1500, verbose_name='Описание ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_img',
            field=models.ImageField(upload_to='fabric_images/%Y/%m/%d', verbose_name='Образец ткани'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1_description',
            field=models.CharField(max_length=500, verbose_name='Описание опции 1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_description',
            field=models.CharField(max_length=500, verbose_name='Описание опции 2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок опции (не обязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_for_delivery_2',
            field=models.BooleanField(default=True, verbose_name='Доставим за 2 дня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_for_delivery_28',
            field=models.BooleanField(default=True, verbose_name='Доставим за 28 дней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_in_showroom',
            field=models.BooleanField(default=True, verbose_name='Есть в шоуруме'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carcas_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Каркас'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.ImageField(blank=True, null=True, upload_to='closeups/', verbose_name='Крупный фрагмент справа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.fabric', verbose_name='Название ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Конструктивные особенности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='linen_drawer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бельевой ящик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanism_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Механизм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.option', verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='paws_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ножки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Файл PDF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=True, verbose_name='Отображать в карусели "Популярные"'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (распродажа)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное название товара (напр. Угловой диван Consono)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside_pillow',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение подушек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scheme',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleep_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d'),
        ),
        migrations.AddIndex(
            model_name='popoverfeatures',
            index=models.Index(fields=['popover_name'], name='product_pop_popover_de2627_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderinterior',
            index=models.Index(fields=['slint_name'], name='product_sli_slint_n_edcb20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'product_slug', '-created'], name='product_pro_id_d2cb84_idx'),
        ),
        migrations.DeleteModel(
            name='FabricIconChange',
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior',
            field=models.ForeignKey(blank=True, db_column='products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.sliderinterior', verbose_name='Слайдер с интерьерами'),
        ),
    ]
