# Generated by Django 4.1.12 on 2023-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabriciconchange',
            options={'ordering': ['product_fabric_name'], 'verbose_name': 'Иконка переключения ткани', 'verbose_name_plural': 'Иконки переключения ткани'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabriciconchange',
            name='product_fabric_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_img',
            field=models.ImageField(upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fabriciconchange',
            name='product_fabric_icon',
            field=models.ImageField(upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.ImageField(blank=True, upload_to='closeups/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
