# Generated by Django 4.1.13 on 2023-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel_1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/%Y/%m/%d', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_1',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 1 | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_2',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 2 | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_3',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 3 | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_4',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 4 | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_5',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 5 | десктоп'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_1',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 1 | мобильный'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_2',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 2 | мобильный'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_3',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 3 | мобильный'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_4',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 4 | мобильный'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_5',
            field=models.ImageField(default='static/img/popovers_arm.png', upload_to='carousel/%Y/%m/%d', verbose_name='Изображение 4 | мобильный'),
        ),
    ]
