# Generated by Django 4.1.12 on 2023-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_remove_product_carousel_item_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closeup',
            field=models.ImageField(default=2023, upload_to='images/%Y/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_about',
            field=models.ImageField(upload_to='fabric_images/%Y/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_icon',
            field=models.ImageField(upload_to='fabric_images/%Y/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_img',
            field=models.ImageField(upload_to='fabric_images/%Y/'),
        ),
    ]
