# Generated by Django 5.0 on 2023-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_popoverfeatures_sliderinterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_fabric_icon_1',
            field=models.SlugField(max_length=100, null=True, verbose_name='Название ткани №1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_fabric_icon_2',
            field=models.SlugField(max_length=100, null=True, verbose_name='Название ткани №2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_fabric_icon_3',
            field=models.SlugField(max_length=100, null=True, verbose_name='Название ткани №3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_fabric_icon_4',
            field=models.SlugField(max_length=100, null=True, verbose_name='Название ткани №4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_fabric_icon_5',
            field=models.SlugField(max_length=100, null=True, verbose_name='Название ткани №5'),
        ),
    ]
