# Generated by Django 4.1.12 on 2023-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_fabriciconchange_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
