# Generated by Django 4.1.12 on 2023-11-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_closeup_alter_fabric_product_fabric_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=350)),
                ('option_1_img', models.ImageField(upload_to='options/')),
                ('option_1_description', models.CharField(max_length=500)),
                ('option_2_img', models.ImageField(upload_to='options/')),
                ('option_2_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['option_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_ptr',
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ManyToManyField(db_column='fabric_icons', related_name='fabric_icons', to='product.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_current',
            field=models.ForeignKey(db_column='fabric_current', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_current', to='product.fabric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_about',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_icon',
            field=models.ImageField(upload_to='fabric_images/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_img',
            field=models.ImageField(upload_to='fabric_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.ImageField(upload_to='closeups/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['option_name'], name='product_opt_option__ae3011_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.option'),
        ),
    ]
