# Generated by Django 5.0 on 2023-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug_fabric_icon_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=30, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(max_length=30, verbose_name='Коллекция (Латиницей, с большой буквы)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(max_length=30, null=True, unique=True, verbose_name='URL'),
        ),
    ]
