# Generated by Django 4.1.12 on 2023-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_option_remove_product_category_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carcas_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_items',
            field=models.ManyToManyField(blank=True, related_name='carousel_items', to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_items_mob',
            field=models.ManyToManyField(blank=True, related_name='carousel_items_mob', to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.ImageField(blank=True, null=True, upload_to='closeups/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='linen_drawer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanism_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='paws_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside_pillow',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='scheme',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleep_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior',
            field=models.ManyToManyField(blank=True, related_name='slider_interior', to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_mob',
            field=models.ManyToManyField(blank=True, related_name='slider_interior_mob', to='product.productimage'),
        ),
    ]
