# Generated by Django 5.0 on 2023-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='carousel_images/%Y/%m/%d'),
        ),
    ]
