# Generated by Django 4.1.12 on 2023-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_depth',
            new_name='depth',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_width',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_for_delivery_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_for_delivery_28',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_in_showroom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_1',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_2',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_3',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_4',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_5',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_1',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_2',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_3',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_4',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_item_mob_5',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='closeup',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='the link to images', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_img',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='scheme',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_1',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_1_mob',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_2',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_2_mob',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_3',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_3_mob',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_4',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior_4_mob',
            field=models.CharField(default='the link to images', max_length=150),
            preserve_default=False,
        ),
    ]
