# Generated by Django 4.1.12 on 2023-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_fabric_about',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_img',
            field=models.ImageField(blank=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='pr', max_length=350),
        ),
    ]
