# Generated by Django 4.1.12 on 2023-10-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_prod_depth_product_depth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_full_name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_name_b60cd1_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_full_name',
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_delivery_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_delivery_28',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_in_showroom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_full_name'], name='product_pro_product_63afbd_idx'),
        ),
    ]
