# Generated by Django 4.1.12 on 2023-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_product_fabric_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_fabric_icon',
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_4',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_fabric_icon_5',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='FabricIconChange',
        ),
    ]
