# Generated by Django 4.1.12 on 2023-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carcas_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='linen_drawer',
            field=models.CharField(default='Нет', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mechanism_type',
            field=models.CharField(default='Нет', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='paws_type',
            field=models.CharField(default='Нет', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.CharField(default='Нет', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_inside',
            field=models.CharField(default='Нет', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_inside_pillow',
            field=models.CharField(default='Нет', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sleep_place',
            field=models.CharField(default='Нет', max_length=50),
            preserve_default=False,
        ),
    ]
