# Generated by Django 5.0 on 2023-12-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_product_alter_product_carousel_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_1',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_2',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_3',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_4',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_mob_1',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_mob_2',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_mob_3',
        ),
        migrations.RemoveField(
            model_name='sliderinterior',
            name='slint_img_mob_4',
        ),
        migrations.AddField(
            model_name='sliderinterior',
            name='interior_items',
            field=models.ManyToManyField(related_name='interior_items', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='sliderinterior',
            name='interior_items_mob',
            field=models.ManyToManyField(blank=True, related_name='interior_items_mob', to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
