# Generated by Django 4.1.12 on 2023-11-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_product_fabric_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('producttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('producttype', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
                'ordering': ['producttype'],
            },
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['producttype'], name='product_pro_product_c661b4_idx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttype'),
            preserve_default=False,
        ),
    ]
