# Generated by Django 4.1.12 on 2023-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_carcas_type_product_linen_drawer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=550),
        ),
    ]
