# Generated by Django 5.0 on 2023-12-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_sliderinterior_slint_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slider_interior',
        ),
        migrations.AddField(
            model_name='product',
            name='interior_items',
            field=models.ManyToManyField(blank=True, related_name='interior_items', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='interior_items_mob',
            field=models.ManyToManyField(blank=True, related_name='interior_items_mob', to='product.productimage'),
        ),
        migrations.DeleteModel(
            name='SliderInterior',
        ),
    ]
