# Generated by Django 5.0 on 2023-12-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_slider_interior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carousel_items',
            field=models.ManyToManyField(related_name='carousel_items', to='product.productimage', verbose_name='Слайдер с товаром | десктоп'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_items_mob',
            field=models.ManyToManyField(blank=True, related_name='carousel_items_mob', to='product.productimage', verbose_name='Слайдер с товаром | мобильный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='interior_items',
            field=models.ManyToManyField(blank=True, related_name='interior_items', to='product.productimage', verbose_name='Слайдер с интерьером | десктоп'),
        ),
        migrations.AlterField(
            model_name='product',
            name='interior_items_mob',
            field=models.ManyToManyField(blank=True, related_name='interior_items_mob', to='product.productimage', verbose_name='Слайдер с интерьером | мобильный'),
        ),
    ]
