# Generated by Django 4.1.12 on 2023-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carousel_item_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_5',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_mob_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_mob_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_mob_3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_mob_4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='carousel_item_mob_5',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_img',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_1_mob',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_2_mob',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_3_mob',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_interior_4_mob',
            field=models.CharField(max_length=250),
        ),
    ]
