# Generated by Django 5.0 on 2023-12-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_carousel_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
