# Generated by Django 4.1.12 on 2023-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_carousel_item_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_fabric_about',
            field=models.CharField(max_length=1000),
        ),
    ]
