# Generated by Django 5.0 on 2023-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_icon_available_for_delivery_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon_available_for_delivery_2',
            field=models.FileField(blank=True, null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Доставим за 2 дня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_available_for_delivery_28',
            field=models.FileField(blank=True, null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Доставим за 28 дней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_available_in_showroom',
            field=models.FileField(blank=True, null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Есть в шоуруме'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_is_new',
            field=models.FileField(blank=True, null=True, upload_to='status_icons/%Y/%m/%d', verbose_name='Иконка | Новый'),
        ),
    ]
