# Generated by Django 5.0 on 2023-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_icon_available_for_delivery_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_1',
            field=models.ImageField(blank=True, default='fabric_icons/2023/12/06/CAMBRIDGE_600.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_2',
            field=models.ImageField(blank=True, default='fabric_icons/2023/12/06/JAZZ_01.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_3',
            field=models.ImageField(blank=True, default='fabric_icons/2023/12/06/JAZZ_21.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_4',
            field=models.ImageField(blank=True, default='fabric_icons/2023/12/06/PIXEL_FOREST.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_5',
            field=models.ImageField(blank=True, default='fabric_icons/2023/12/06/VELUTTO_32.png', null=True, upload_to='fabric_icons/%Y/%m/%d', verbose_name='Иконка переключения ткани № 5'),
        ),
    ]
