# Generated by Django 4.1.12 on 2023-12-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricIconChange',
            fields=[
                ('fabric_icon_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_fabric_icon', models.ImageField(blank=True, null=True, upload_to='fabric_images/%Y/%m/%d', verbose_name='Иконка переключения ткани')),
            ],
            options={
                'verbose_name': 'Иконка переключения ткани',
                'verbose_name_plural': 'Иконки переключения ткани',
                'ordering': ['product_fabric_icon_name'],
            },
        ),
        migrations.CreateModel(
            name='SliderInterior',
            fields=[
                ('slint_id', models.AutoField(primary_key=True, serialize=False)),
                ('slint_name', models.CharField(max_length=350, verbose_name='Название слайдера')),
                ('slint_img_1', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 1')),
                ('slint_img_2', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 2')),
                ('slint_img_3', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 3')),
                ('slint_img_4', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Десктоп | Изображение 4')),
                ('slint_img_mob_1', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 1')),
                ('slint_img_mob_2', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 2')),
                ('slint_img_mob_3', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 3')),
                ('slint_img_mob_4', models.ImageField(upload_to='slider_interior/%Y/%m/%d', verbose_name='Мобильный | Изображение 4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
            ],
            options={
                'verbose_name': 'Слайдер с интерьерами',
                'verbose_name_plural': 'Слайдеры с интерьерами',
                'ordering': ['slint_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior_mob',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория (латиницей, для БД: arm, str, k1r и т.п.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=50, verbose_name='Категория (по-русски, для отображения на сайте)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(max_length=50, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_name',
            field=models.CharField(max_length=50, verbose_name='Название ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_about',
            field=models.CharField(max_length=1500, verbose_name='Описание ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_fabric_img',
            field=models.ImageField(upload_to='fabric_images/%Y/%m/%d', verbose_name='Образец ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AlterField(
            model_name='option',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1_description',
            field=models.CharField(max_length=500, verbose_name='Описание опции 1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_description',
            field=models.CharField(max_length=500, verbose_name='Описание опции 2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_img',
            field=models.ImageField(upload_to='options/%Y/%m/%d', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок опции (не обязательно)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_for_delivery_2',
            field=models.BooleanField(default=True, verbose_name='Доставим за 2 дня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_for_delivery_28',
            field=models.BooleanField(default=True, verbose_name='Доставим за 28 дней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_in_showroom',
            field=models.BooleanField(default=True, verbose_name='Есть в шоуруме'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carcas_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Каркас'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closeup',
            field=models.ImageField(blank=True, upload_to='closeups/', verbose_name='Крупный фрагмент справа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection', verbose_name='Коллекиция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_name',
            field=models.ForeignKey(db_column='slider_products', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.fabric', verbose_name='Название ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Конструктивные особенности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='linen_drawer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бельевой ящик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanism_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Механизм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.option', verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='paws_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ножки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Файл PDF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=True, verbose_name='Отображать в карусели "Популярные"'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (распродажа)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_about',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Описание ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_img',
            field=models.ImageField(blank=True, upload_to='fabric_images/%Y/%m/%d', verbose_name='Образец ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название товара (напр. Кресло Consono)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inside_pillow',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наполнение подушек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scheme',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleep_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_interior',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddIndex(
            model_name='sliderinterior',
            index=models.Index(fields=['slint_name'], name='product_sli_slint_n_edcb20_idx'),
        ),
        migrations.AddField(
            model_name='fabriciconchange',
            name='product_fabric_icon_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fabric', verbose_name='Название ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_icon_1', to='product.fabriciconchange'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_icon_2', to='product.fabriciconchange'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_icon_3', to='product.fabriciconchange'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_icon_4', to='product.fabriciconchange'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabric_icon_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_icon_5', to='product.fabriciconchange'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_interior',
            field=models.ForeignKey(blank=True, db_column='products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.sliderinterior', verbose_name='Слайдер с интерьерами'),
        ),
        migrations.AddIndex(
            model_name='fabriciconchange',
            index=models.Index(fields=['product_fabric_icon'], name='product_fab_product_ca6b7e_idx'),
        ),
    ]
