# Generated by Django 4.1.12 on 2023-12-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_fabriciconchange_sliderinterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopOverFeatures',
            fields=[
                ('popover_id', models.AutoField(primary_key=True, serialize=False)),
                ('popover_name', models.CharField(blank=True, max_length=350, null=True, verbose_name='Название фичи')),
                ('popover_1_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 1')),
                ('popover_1_description', models.CharField(max_length=500, verbose_name='Описание фичи 1')),
                ('popover_2_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 2')),
                ('popover_2_description', models.CharField(max_length=500, verbose_name='Описание фичи 2')),
                ('popover_3_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 3')),
                ('popover_3_description', models.CharField(max_length=500, verbose_name='Описание фичи 3')),
                ('popover_4_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 4')),
                ('popover_4_description', models.CharField(max_length=500, verbose_name='Описание фичи 4')),
                ('popover_5_img', models.ImageField(upload_to='popover_features/%Y/%m/%d', verbose_name='Картинка фичи 5')),
                ('popover_5_description', models.CharField(max_length=500, verbose_name='Описание фичи 5')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popoverfeatures', to='product.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Фича поп-овер',
                'verbose_name_plural': 'Фичи поп-овер',
                'ordering': ['popover_name'],
            },
        ),
        migrations.AddIndex(
            model_name='popoverfeatures',
            index=models.Index(fields=['popover_name'], name='product_pop_popover_de2627_idx'),
        ),
    ]
