# Generated by Django 4.1.12 on 2023-12-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_fabriciconchange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriciconchange',
            name='fabric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_icon_name', to='product.fabric', verbose_name='Название ткани'),
        ),
    ]
