# Generated by Django 4.1.12 on 2023-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_fabriciconchange_fabric_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabriciconchange',
            options={'ordering': ['product_fabric_name'], 'verbose_name': 'Иконка переключения ткани', 'verbose_name_plural': 'Иконки переключения ткани'},
        ),
        migrations.RemoveIndex(
            model_name='fabriciconchange',
            name='product_fab_fabric__34f8d6_idx',
        ),
        migrations.RemoveField(
            model_name='fabriciconchange',
            name='fabric_name',
        ),
        migrations.AddField(
            model_name='fabriciconchange',
            name='product_fabric_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название ткани'),
        ),
        migrations.AddIndex(
            model_name='fabriciconchange',
            index=models.Index(fields=['product_fabric_name'], name='product_fab_product_6c40be_idx'),
        ),
    ]
