# Generated by Django 4.1.12 on 2023-12-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_fabriciconchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='producttype',
            field=models.CharField(default='Аксессуар', max_length=50, verbose_name='Название категории (по-русски, в ЕДИНСТВЕННОМ числе)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=50, verbose_name='Название категории (по-русски, в МНОЖЕСТВЕННОМ числе)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='product.category', verbose_name='Тип продукта'),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
