# Generated by Django 4.1.12 on 2023-12-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_producttype_alter_category_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_fabric_about',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_fabric_img',
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_category_page',
            field=models.BooleanField(default=True, verbose_name='Отображать в выдаче категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='producttype',
            field=models.CharField(default='Аксессуар', max_length=50, verbose_name='Название категории (то же, в ЕДИНСТВЕННОМ числе)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное название товара (напр. Угловой диван Consono)'),
        ),
    ]
