# Generated by Django 4.1.12 on 2023-12-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_popoverfeatures_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
