# Generated by Django 4.1.12 on 2023-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_category_cat_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='category_slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='producttype',
            field=models.CharField(max_length=50, verbose_name='Название категории (то же, в ЕДИНСТВЕННОМ числе)'),
        ),
    ]
