# Generated by Django 4.1.12 on 2023-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_rename_cat_slug_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
