# Generated by Django 4.1.12 on 2023-12-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_category_category_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_id_7c37c2_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'product_slug', '-created'], name='product_pro_id_d2cb84_idx'),
        ),
    ]
