# Generated by Django 4.1.12 on 2023-12-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_product_product_pro_id_7c37c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30, verbose_name='Сокращенно латиницей (arm, str, k1r и т.п.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(max_length=30, verbose_name='Коллекция'),
        ),
    ]
