# Generated by Django 4.1.12 on 2023-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_collection_collection_slug_alter_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(max_length=30),
        ),
    ]
