# Generated by Django 4.1.12 on 2023-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_collection_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Повторите'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(max_length=30, verbose_name='Коллекция (Латиницей)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Повторите'),
        ),
    ]
